### ISSUE TITLE
Add search for band/event names

### ISSUE THREAD

**Issue by jochenwuerfel** [Knochenmarc/metal-in-leipzig#6]
Users can quickly look up for specific band or event names, lookup should be as wildcard so users won't need to type them - upper/lower case shouldn't make any difference.
E.g. search for "ALE" should show results for  "Alestorm" as well as "Halestorm".
Consider maybe cross functionality with #1 and #3

**Comment by Knochenmarc** [comment]
At the moment this site works without a web backend. So the only option of a search would be within the browser, based on javascript. That is definitely possible. But I was actually aiming for a nojs website. >.<
Of cause I'd like to use this as well. So I should look into some simple and optional js solution. Maybe a little searchfield with a little dropdown below.

**Comment by jochenwuerfel** [comment]
Sounds great.. and a site without any shenanigans is always great 🥳

**Comment by Knochenmarc** [comment]
Well, all events are just on a single page now. Just use Crtl+F? :D

**Comment by jochenwuerfel** [comment]
That's a solution, thanks!
